# Modifying Datasets in the Folium Project for SQL Analysis

In [31]:
# INSTALL LIBRARIES

import pandas as pd

In [44]:
# Import the dataset for New York City, NY
# Note: For the purposes of this project in order to visualize the map, rows where the latitude and longitude values were NaN or 0
# were deleted

df_new_york_citations = pd.read_csv(r'C:\Users\jksmi\Downloads\Folium Project\DOHMH_New_York_City_Restaurant_Inspection_Results_clean.csv')
df_new_york_citations

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE,Latitude,Longitude
0,41224985,BENJAMIN STEAK HOUSE,Manhattan,52,EAST 41 STREET,10017,2122979177,Steakhouse,1/31/2020,Violations were cited in the following area(s).,04N,Filth flies or food/refuse/sewage-associated (...,Critical,13.0,A,1/31/2020,10/8/2021,Cycle Inspection / Initial Inspection,40.751886,-73.979214
1,50080154,RICHMOND REPUBLIC,Staten Island,4459,AMBOY ROAD,10312,3473302480,American,10/18/2018,Violations were cited in the following area(s).,06D,"Food contact surface not properly washed, rins...",Critical,22.0,NaN,NaN,10/8/2021,Pre-permit (Operational) / Initial Inspection,40.544380,-74.162347
2,50068816,BROOKLYN PIZZA MARKET,Brooklyn,267,SMITH STREET,11231,9176973215,Pizza,12/8/2018,Violations were cited in the following area(s).,08B,Covered garbage receptacle not provided or ina...,Not Critical,13.0,A,12/8/2018,10/8/2021,Cycle Inspection / Initial Inspection,40.682755,-73.993139
3,50013915,VANILLA CAFE,Queens,9918,37TH AVE,11368,7185051480,Spanish,1/10/2019,Violations were cited in the following area(s).,09C,Food contact surface not properly maintained.,Not Critical,9.0,A,1/10/2019,10/8/2021,Cycle Inspection / Initial Inspection,40.752317,-73.867939
4,41205309,JOE G RESTAURANT (DA VINCI HOTEL),Manhattan,244,WEST 56 STREET,10019,2127653160,Italian,8/17/2018,Violations were cited in the following area(s).,04M,Live roaches present in facility's food and/or...,Critical,21.0,NaN,NaN,10/8/2021,Cycle Inspection / Initial Inspection,40.765659,-73.982499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376635,50066796,ONE STATION PLAZA,Queens,21310,41ST AVE,11361,7182240060,American,12/19/2019,Violations were cited in the following area(s).,04L,Evidence of mice or live mice present in facil...,Critical,9.0,NaN,NaN,10/8/2021,Cycle Inspection / Initial Inspection,40.763515,-73.771705
376636,50088958,GOPCHANG STORY,Queens,16018,NORTHERN BLVD,11358,7186873001,Korean,10/28/2019,Violations were cited in the following area(s).,06C,Food not protected from potential source of co...,Critical,24.0,NaN,NaN,10/8/2021,Cycle Inspection / Initial Inspection,40.762792,-73.805280
376637,50088958,GOPCHANG STORY,Queens,16018,NORTHERN BLVD,11358,7186873001,Korean,10/28/2019,Violations were cited in the following area(s).,06C,Food not protected from potential source of co...,Critical,24.0,NaN,NaN,10/8/2021,Cycle Inspection / Initial Inspection,40.762792,-73.805280
376638,50088958,GOPCHANG STORY,Queens,16018,NORTHERN BLVD,11358,7186873001,Korean,10/28/2019,Violations were cited in the following area(s).,06C,Food not protected from potential source of co...,Critical,24.0,NaN,NaN,10/8/2021,Cycle Inspection / Initial Inspection,40.762792,-73.805280
376639,41321647,PARK AVENUE LUNCHEONETTE,Brooklyn,131,PARK AVENUE,11205,7186436434,Latin American,8/1/2017,Violations were cited in the following area(s).,06D,"Food contact surface not properly washed, rins...",Critical,43.0,NaN,NaN,10/8/2021,Cycle Inspection / Initial Inspection,40.696270,-73.974305

In [45]:
# Due to the large size of the dataset (376640 rows) I will reduce the dataframe to 10000 citations
# Pulling only the 1st 10000 crimes in the df_new_york_citations dataframe

limit = 10000
df_new_york_citations = df_new_york_citations.iloc[0:limit, :]

In [47]:
# Confirm that dataframe has been reduced

df_new_york_citations.shape

(10000, 20)

In [48]:
# Listing the columns in the dataframe

df_new_york_citations.columns.tolist()

['CAMIS',
 'DBA',
 'BORO',
 'BUILDING',
 'STREET',
 'ZIPCODE',
 'PHONE',
 'CUISINE DESCRIPTION',
 'INSPECTION DATE',
 'ACTION',
 'VIOLATION CODE',
 'VIOLATION DESCRIPTION',
 'CRITICAL FLAG',
 'SCORE',
 'GRADE',
 'GRADE DATE',
 'RECORD DATE',
 'INSPECTION TYPE',
 'Latitude',
 'Longitude']

In [49]:
# Now to update the column names in the dataset to make working with the dataset easier

new_column_list = ('id_number', 'restaurant_name', 'borough', 'building_number', 'street_name', 'zipcode', 'phone', 'cuisine_description', 'inspection_date', 'action', 'violation_code', 'violation_description', 'critical_flag', 'score', 'grade', 'grade_date', 'record_date', 'inspection_date', 'latitude', 'longitude')
df_new_york_citations.columns = new_column_list

In [50]:
# Now to check to see if new column names were updated in the dataframe

df_new_york_citations.columns.tolist()

['id_number',
 'restaurant_name',
 'borough',
 'building_number',
 'street_name',
 'zipcode',
 'phone',
 'cuisine_description',
 'inspection_date',
 'action',
 'violation_code',
 'violation_description',
 'critical_flag',
 'score',
 'grade',
 'grade_date',
 'record_date',
 'inspection_date',
 'latitude',
 'longitude']

In [51]:
# Now to read the new df_new_york_citations dataframe to an excel file

df_new_york_citations.to_excel(r'C:\Users\jksmi\Downloads\Folium Project\Part2\df_new_york_citations.xlsx', index=False)

In [38]:
# Import the dataset for Chicago
# Note: For the purposes of this project in order to visualize the map, rows where the latitude and longitude values were NaN 
# were deleted

df_chicago_incidents = pd.read_csv(r'C:\Users\jksmi\Downloads\Folium Project\crimes_one_year_prior_to_present_clean.csv')
df_chicago_incidents

,date_of_occurrence,case_number,block,iucr,primary_description,secondary_description,location_description,arrest,domestic,beat,ward,fbi_cd,x_coordinate,y_coordinate,latitude,longitude,location
0,9/29/2021 23:52,JE392324,003XX S SACRAMENTO BLVD,1320,CRIMINAL DAMAGE,TO VEHICLE,GAS STATION,N,Y,1124,28.0,14,1156434,1898301,41.876720,-87.701088,"(41.876720197, -87.701088107)"
1,9/29/2021 23:50,JE392344,026XX W CERMAK RD,320,ROBBERY,STRONG ARM - NO WEAPON,STREET,N,N,1023,24.0,3,1159207,1889299,41.851961,-87.691154,"(41.851961298, -87.691153739)"
2,9/29/2021 23:48,JE392074,110XX S BISHOP ST,110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,N,N,2234,34.0,01A,1168527,1831333,41.692699,-87.658616,"(41.692698911, -87.658615989)"
3,9/29/2021 23:40,JE392296,041XX S WABASH AVE,560,ASSAULT,SIMPLE,STREET,N,N,213,3.0,08A,1177405,1877502,41.819197,-87.624720,"(41.81919655, -87.624719873)"
4,9/29/2021 23:36,JE392303,009XX W 70TH ST,2024,NARCOTICS,POSSESS - HEROIN (WHITE),STREET,Y,N,733,6.0,18,1171431,1858425,41.766980,-87.647193,"(41.766980264, -87.647193248)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200083,9/30/2020 6:00,JD384948,010XX S ASHLAND AVE,1581,SEX OFFENSE,NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL...,APARTMENT,N,N,1231,28.0,17,1165888,1895568,41.869024,-87.666454,"(41.86902427, -87.666453984)"
200084,9/30/2020 6:00,JD407205,067XX S CORNELL AVE,1110,DECEPTIVE PRACTICE,BOGUS CHECK,APARTMENT,N,N,332,5.0,11,1188363,1860651,41.772701,-87.585060,"(41.772701185, -87.585060362)"
200085,9/30/2020 5:50,JD383827,070XX S DORCHESTER AVE,810,THEFT,OVER $500,APARTMENT,N,Y,321,5.0,6,1186752,1858681,41.767334,-87.591028,"(41.767333643, -87.591028093)"
200086,9/30/2020 5:30,JD387309,027XX S DRAKE AVE,910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,N,N,1032,22.0,7,1153145,1885563,41.841832,-87.713502,"(41.841831511, -87.713501996)"
200087,9/30/2020 5:05,JD383825,003XX S CICERO AVE,860,THEFT,RETAIL THEFT,GAS STATION,Y,N,1533,28.0,6,1144438,1898165,41.876581,-87.745138,"(41.876581037, -87.745137513)"

In [39]:
# Listing the columns in the dataframe

df_chicago_incidents.columns.tolist()

['date_of_occurrence',
 'case_number',
 'block',
 'iucr',
 'primary_description',
 'secondary_description',
 'location_description',
 'arrest',
 'domestic',
 'beat',
 'ward',
 'fbi_cd',
 'x_coordinate',
 'y_coordinate',
 'latitude',
 'longitude',
 'location']

In [40]:
# Checking to see the shape of the dataframe

df_chicago_incidents.shape

(200088, 17)

In [41]:
# Again reducing the dataframe to 10000 crimes due to the dataframe containing 200088 rows
# Pulling only the 1st 10000 crimes in the df_chicago_incidents dataframe

limit = 10000
df_chicago_incidents = df_chicago_incidents.iloc[0:limit, :]

In [42]:
# Confirm that dataframe has been reduced

df_chicago_incidents.shape

(10000, 17)

In [43]:
# Now to read the new df_chicago_incidents dataframe to an excel file

df_chicago_incidents.to_excel(r'C:\Users\jksmi\Downloads\Folium Project\Part2\df_chicago_incidents.xlsx', index=False)